name: Integration test pyzeebe

on: [push, pull_request]

jobs:
  test:
    env:
      ZEEBE_ADDRESS: "zeebe:26500"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zeebe-version: [ "1.0.0-rc3" ]

    container: python:3.6

    services:
      zeebe:
        image: camunda/zeebe:${{ matrix.zeebe-version }}
        ports:
          - 26500/tcp


    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Run integration tests
        run: |
          pipenv run pytest tests/integration
